'use strict';

module.exports = {
    MONGODB_USERNAME: process.env.MONGODB_USERNAME,
    MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
    MONGODB_ENDPOINT: process.env.MONGODB_ENDPOINT,
    AWS_REGION: process.env.AWS_REGION,
    MYSQL_HOST: process.env.MYSQL_HOST,
    MYSQL_PORT: process.env.MYSQL_PORT,
    MYSQL_USER: process.env.MYSQL_USER,
    MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
    MYSQL_SSL: process.env.MYSQL_SSL,
    MYSQL_DATABASE_NAME: process.env.MYSQL_DATABASE_NAME,
    MYSQL_TABLE_NAME: process.env.MYSQL_TABLE_NAME,
    MYSQL_READ_THROUGHPUT: process.env.MYSQL_READ_THROUGHPUT,
    MONGODB_COLLECTION_NAME: process.env.MONGODB_COLLECTION_NAME,
    MONGODB_DATABASE_NAME: process.env.MONGODB_DATABASE_NAME,
    MAPPER_BUCKET_NAME: process.env.MAPPER_BUCKET_NAME,
    MAPPER_OBJECT_KEY: process.env.MAPPER_OBJECT_KEY
};